before_build:
  - nuget restore %solution_name%
  
environment:
  matrix:
  - solution_name: sem3\hw1.1\hw1.1.sln
  - solution_name: sem3\hw2.1\hw2.1.sln
  - solution_name: sem3\hw3.1\hw3.1.sln
  - solution_name: sem3\hw4.1\hw4.1.sln
  
build_script:
  - msbuild %solution_name%

test_script:
  - dotnet test %solution_name%
